
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
      jdbc:
        lob:
          non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

